---
# tasks file for logstash-role

- include: logstash_requirements.yml
  tags:
   - logstash_req

- include: logstash_installation_Debian.yml
  when: ansible_os_family == "Debian"
  tags:
   - logstash_install

- include: logstash_installation_RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
   - logstash_install

- include: logstash_configuration.yml
  tags:
   - logstash_conf
